//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicYear
    {
        public int Id { get; set; }
        public string Academic_Year_En { get; set; }
        public string Academic_Year_Ar { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsResultPublished { get; set; }
        public Nullable<bool> isCurrent { get; set; }
        public string ACStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
