//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> ParentLevel { get; set; }
        public Nullable<bool> VoucherEntry { get; set; }
        public Nullable<bool> FinalAccount { get; set; }
        public Nullable<int> AccountGroup { get; set; }
        public Nullable<int> SubGroup { get; set; }
        public Nullable<int> AccCategory { get; set; }
        public Nullable<bool> ShowChild { get; set; }
        public Nullable<bool> ISDefault { get; set; }
        public Nullable<bool> AllowEntry { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<bool> Editable { get; set; }
        public Nullable<long> UserTrackID { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<int> AOrderNo { get; set; }
        public Nullable<int> CCID { get; set; }
        public Nullable<bool> InVisible { get; set; }
        public Nullable<decimal> SortField { get; set; }
        public Nullable<bool> ShowRow { get; set; }
        public string fn { get; set; }
        public string ln { get; set; }
        public string mn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> PermanentDelete { get; set; }
    }
}
