//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_AbsentMaster
    {
        public int Id { get; set; }
        public Nullable<int> ReasonType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Approve1 { get; set; }
        public string Remarks1 { get; set; }
        public Nullable<bool> Approve2 { get; set; }
        public string Remarks2 { get; set; }
        public Nullable<bool> Approve3 { get; set; }
        public string Remarks3 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> PermanentDelete { get; set; }
    }
}
