//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplainLog
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string ContactBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Class { get; set; }
        public string CellNo { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string ActionTaken { get; set; }
        public string InformPerson { get; set; }
        public bool IsConsulted { get; set; }
        public Nullable<System.DateTime> InformDate { get; set; }
        public string ParentsComments { get; set; }
        public string FollowUp { get; set; }
    }
}
