//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalResourceFile
    {
        public int Id { get; set; }
        public Nullable<int> MasterId { get; set; }
        public string FileExtnsion { get; set; }
        public string ShowFileName { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Category { get; set; }
    
        public virtual DigitalResourceMaster DigitalResourceMaster { get; set; }
    }
}
