//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalResourceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DigitalResourceMaster()
        {
            this.DigitalResourceClasses = new HashSet<DigitalResourceClass>();
            this.DigitalResourceFiles = new HashSet<DigitalResourceFile>();
        }
    
        public int Id { get; set; }
        public string title { get; set; }
        public string DescriptionShort { get; set; }
        public string DescriptionLong { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsPermanentDelete { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string AdminRemarks { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CategoryIdMajorParent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DigitalResourceClass> DigitalResourceClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DigitalResourceFile> DigitalResourceFiles { get; set; }
        public virtual LessonPlanCategory LessonPlanCategory { get; set; }
    }
}
