//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_SubComments
    {
        public int Id { get; set; }
        public string AcademicYear { get; set; }
        public int SubGroupId { get; set; }
        public string Code { get; set; }
        public string GenComments { get; set; }
        public string SkillComments { get; set; }
        public Nullable<decimal> MarkFrom { get; set; }
        public Nullable<decimal> MarkTo { get; set; }
        public string School { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
