//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_SubTeacherPeriodMapping
    {
        public int Id { get; set; }
        public string ClassId { get; set; }
        public string Division { get; set; }
        public string School { get; set; }
        public string SubjectId { get; set; }
        public string Options { get; set; }
        public string SubOption { get; set; }
        public string Day { get; set; }
        public string Period { get; set; }
        public string StaffCode { get; set; }
        public string StaffName { get; set; }
        public string RoomNo { get; set; }
    }
}
