//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_Grading
    {
        public int Id { get; set; }
        public Nullable<int> MarkFrom { get; set; }
        public Nullable<int> Markto { get; set; }
        public string Grade { get; set; }
        public string GradePoint { get; set; }
        public string Groups { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
