//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_subjectGroup
    {
        public string Id { get; set; }
        public int TermId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string School { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> Max { get; set; }
        public Nullable<int> Min { get; set; }
        public string Marktype { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<int> Ono { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
