//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_MarkEntry
    {
        public int Id { get; set; }
        public int Term_Id { get; set; }
        public int Student_id { get; set; }
        public int SubjGroup_Id { get; set; }
        public decimal Mark { get; set; }
        public Nullable<decimal> Mark2 { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string School { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<bool> Is_sent_For_Approval { get; set; }
        public Nullable<bool> Is_Approved { get; set; }
        public string SkillComment { get; set; }
        public string GenComment { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string Approvedby { get; set; }
    }
}
