//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_ClassTimeTable
    {
        public int CTTID { get; set; }
        public string Class { get; set; }
        public string Division { get; set; }
        public string schoolId { get; set; }
        public string AcademicYear { get; set; }
        public string Day { get; set; }
        public string Period { get; set; }
        public string Subject { get; set; }
        public Nullable<int> RowPos { get; set; }
        public Nullable<int> ColPos { get; set; }
    }
}
