//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_Emp
    {
        public int Id { get; set; }
        public int SchoolId { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public string father_Name { get; set; }
        public string mother_Name { get; set; }
        public string PhoneNo { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Nationality { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public Nullable<System.DateTime> DateofJoining { get; set; }
        public Nullable<int> department { get; set; }
        public Nullable<int> designation { get; set; }
        public string Login_ID { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> basic_salary { get; set; }
        public Nullable<decimal> allounces { get; set; }
        public Nullable<decimal> gras_salary { get; set; }
        public string salary_trans { get; set; }
        public string allounce_detail { get; set; }
        public string bank_exchange { get; set; }
        public Nullable<int> tot_leaves { get; set; }
        public string Passport { get; set; }
        public string emiratId { get; set; }
        public Nullable<System.DateTime> hr_emirtId_ex_date { get; set; }
        public string VisaType { get; set; }
        public Nullable<System.DateTime> visa_strt_Date { get; set; }
        public Nullable<System.DateTime> visa_end_Date { get; set; }
        public string driving_licence1 { get; set; }
        public string driving_licence2 { get; set; }
        public string driving_licence3 { get; set; }
        public string residance_address { get; set; }
        public string marital_status { get; set; }
        public string interview_by { get; set; }
        public string select_by { get; set; }
        public string report_to { get; set; }
        public string Note { get; set; }
        public byte[] pic { get; set; }
        public string picType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string hr_adek_status { get; set; }
        public string hr_adek_title_en { get; set; }
        public string hr_adek_title_ar { get; set; }
        public string hr_adek_cycle { get; set; }
        public string hr_adek_grade { get; set; }
        public string hr_school_visa_title { get; set; }
        public string hr_school_desig_en { get; set; }
        public string hr_school_desig_ar { get; set; }
        public string hr_school_arab_n_arab { get; set; }
        public string hr_school_section { get; set; }
        public string hr_school_dept { get; set; }
    }
}
