//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREmployeeMst
    {
        public int Id { get; set; }
        public string SchoolId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string hr_name { get; set; }
        public string hr_currentposition { get; set; }
        public string hr_currentsalary { get; set; }
        public string hr_nationality { get; set; }
        public string hr_placeofBirth { get; set; }
        public Nullable<System.DateTime> hr_DOB { get; set; }
        public string hr_PaymentMode { get; set; }
        public string hr_SalaryMode { get; set; }
        public string hr_LeavePerYear { get; set; }
        public string hr_state { get; set; }
        public string hr_city { get; set; }
        public string hr_remarks { get; set; }
        public string hr_bank { get; set; }
        public string hr_bankAccount { get; set; }
        public string hr_joinDate { get; set; }
        public string hr_gender { get; set; }
        public string hr_status { get; set; }
        public string hr_ApprovedDate { get; set; }
        public string hr_MinistryStatus { get; set; }
        public string hr_EOSDate { get; set; }
        public string hr_majorSpecialization { get; set; }
        public string hr_minorSpecialization { get; set; }
        public string hr_ticket { get; set; }
        public string hr_TotalAllowance { get; set; }
        public string hr_ContractType { get; set; }
        public string hr_majorSpecializationAr { get; set; }
        public string hr_SubStatus { get; set; }
        public string hr_passportno { get; set; }
        public string hr_placeofissue { get; set; }
        public Nullable<System.DateTime> hr_dateofissue { get; set; }
        public Nullable<System.DateTime> hr_dateofexpire { get; set; }
        public string hr_visatype { get; set; }
        public string hr_visano { get; set; }
        public Nullable<System.DateTime> hr_dateofvisaexpire { get; set; }
        public string hr_basic_salary { get; set; }
        public Nullable<System.DateTime> hr_visaexpire { get; set; }
        public string hr_religion { get; set; }
        public Nullable<System.DateTime> hr_emirtId_ex_date { get; set; }
        public string hr_emirtId_no { get; set; }
        public string hr_spouceplaceofbirth { get; set; }
        public string hr_spoucename { get; set; }
        public string hr_telephon { get; set; }
        public string hr_placeorwork { get; set; }
        public string hr_permtaddress { get; set; }
        public string hr_permttelno { get; set; }
        public string hr_permtmobile { get; set; }
        public string hr_permtemail { get; set; }
        public string hr_presentaddress { get; set; }
        public string hr_presenttelno { get; set; }
        public string hr_presentmobile { get; set; }
        public string hr_presentemail { get; set; }
        public string hr_relativename1 { get; set; }
        public string hr_relativetelnomobile1 { get; set; }
        public string hr_relativename2 { get; set; }
        public string hr_relativetelnomobile2 { get; set; }
        public string hr_sect { get; set; }
        public string hr_sponsor { get; set; }
        public string hr_maritalsatus { get; set; }
        public string hr_seriousillness { get; set; }
        public Nullable<bool> hr_pregnancy { get; set; }
        public Nullable<System.DateTime> hr_deliverydate { get; set; }
        public string hr_spouceoccupation { get; set; }
        public string hr_spoucenationality { get; set; }
        public Nullable<bool> hr_relativwork { get; set; }
        public Nullable<bool> hr_workbefore { get; set; }
        public string hr_leavereason { get; set; }
        public string hr_desireposition { get; set; }
        public string hr_desiresalary { get; set; }
        public Nullable<System.DateTime> hr_desiretostart { get; set; }
        public string hr_desiretypeofaccmodation { get; set; }
        public string hr_desirenofchildren { get; set; }
        public string hr_photoRef { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
