//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequestForm
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Class { get; set; }
        public string StudentCode { get; set; }
        public string CellNo { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> ParentApproval { get; set; }
        public string AdminRemarks { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Term { get; set; }
    }
}
