//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonsPlanMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LessonsPlanMaster()
        {
            this.LessonPlanDetails = new HashSet<LessonPlanDetail>();
        }
    
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Class { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModefiedOn { get; set; }
        public string ModefiedBy { get; set; }
        public Nullable<System.DateTime> LessonPlanFrom { get; set; }
        public Nullable<System.DateTime> LessonPlanTo { get; set; }
        public string HOSRemarks { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public bool IsApproved { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsParmanentDeleted { get; set; }
        public string AssignmentComments { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.DateTime> CreatedFor { get; set; }
    
        public virtual LessonPlanClass LessonPlanClass { get; set; }
        public virtual LessonPlanSubject LessonPlanSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonPlanDetail> LessonPlanDetails { get; set; }
        public virtual LessonPlanCategory LessonPlanCategory { get; set; }
    }
}
