//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonPlanDetail
    {
        public int Id { get; set; }
        public Nullable<int> Master_Id { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string FileExtnsion { get; set; }
        public string ShowFileName { get; set; }
        public string URL { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string HOSRemarks { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public bool IsApproved { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public bool IsParmanentDeleted { get; set; }
        public string Subject { get; set; }
        public string Class { get; set; }
        public string Category { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string TeacherRemarks { get; set; }
        public Nullable<System.DateTime> CreatedFor { get; set; }
    
        public virtual LessonsPlanMaster LessonsPlanMaster { get; set; }
    }
}
