//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Nahda_AttendanceEntities : DbContext
    {
        public Nahda_AttendanceEntities()
            : base("name=Nahda_AttendanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LessonPlanClass> LessonPlanClasses { get; set; }
        public virtual DbSet<LessonPlanSubject> LessonPlanSubjects { get; set; }
        public virtual DbSet<AcademicYear> AcademicYears { get; set; }
        public virtual DbSet<Attendance_AbsentDetails> Attendance_AbsentDetails { get; set; }
        public virtual DbSet<Attendance_AbsentMaster> Attendance_AbsentMaster { get; set; }
        public virtual DbSet<Attendance_Schedule_Details> Attendance_Schedule_Details { get; set; }
        public virtual DbSet<Attendance_Schedule_Master> Attendance_Schedule_Master { get; set; }
        public virtual DbSet<Attendance_Schedule_TimeSlot> Attendance_Schedule_TimeSlot { get; set; }
        public virtual DbSet<Attendance_Sheet> Attendance_Sheet { get; set; }
        public virtual DbSet<Exam_MarkEntry> Exam_MarkEntry { get; set; }
        public virtual DbSet<Exam_SubComments> Exam_SubComments { get; set; }
        public virtual DbSet<Exam_subjectGroup> Exam_subjectGroup { get; set; }
        public virtual DbSet<Exam_subjectGroupRole> Exam_subjectGroupRole { get; set; }
        public virtual DbSet<Exam_subjectGroupRole_detail> Exam_subjectGroupRole_detail { get; set; }
        public virtual DbSet<Exam_Subjects> Exam_Subjects { get; set; }
        public virtual DbSet<Exam_SubjectStudent_Right> Exam_SubjectStudent_Right { get; set; }
        public virtual DbSet<Exam_SubjectStudentRole_Right> Exam_SubjectStudentRole_Right { get; set; }
        public virtual DbSet<hr_department> hr_department { get; set; }
        public virtual DbSet<hr_designation> hr_designation { get; set; }
        public virtual DbSet<hr_Emp> hr_Emp { get; set; }
        public virtual DbSet<HREmployeeMst> HREmployeeMsts { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Student_Class> Student_Class { get; set; }
        public virtual DbSet<Student_StudentDtl> Student_StudentDtl { get; set; }
        public virtual DbSet<Student_StudentMst> Student_StudentMst { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Exam_ClassTimeTable> Exam_ClassTimeTable { get; set; }
        public virtual DbSet<Exam_Grading> Exam_Grading { get; set; }
        public virtual DbSet<Exam_SubTeacherMapping> Exam_SubTeacherMapping { get; set; }
        public virtual DbSet<Exam_SubTeacherPeriodMapping> Exam_SubTeacherPeriodMapping { get; set; }
        public virtual DbSet<Exam_TimeMaster> Exam_TimeMaster { get; set; }
        public virtual DbSet<md_type> md_type { get; set; }
        public virtual DbSet<Student_ClassMaster> Student_ClassMaster { get; set; }
        public virtual DbSet<Student_TeacherClass> Student_TeacherClass { get; set; }
        public virtual DbSet<LessonsPlanMaster> LessonsPlanMasters { get; set; }
        public virtual DbSet<DigitalResourceClass> DigitalResourceClasses { get; set; }
        public virtual DbSet<DigitalResourceFile> DigitalResourceFiles { get; set; }
        public virtual DbSet<LessonPlanDetail> LessonPlanDetails { get; set; }
        public virtual DbSet<LessonPlanCategory> LessonPlanCategories { get; set; }
        public virtual DbSet<DigitalResourceMaster> DigitalResourceMasters { get; set; }
    }
}
