//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewStaffJoining
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string CertifiedBy { get; set; }
        public Nullable<System.DateTime> CertifiedOn { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string HRDesignation { get; set; }
        public string CellNo { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string BankAccountNo { get; set; }
        public string LabourCard { get; set; }
        public Nullable<System.DateTime> LabourCardExpiry { get; set; }
        public string EmaratedIdNo { get; set; }
        public Nullable<System.DateTime> EmaratedIdIssueDate { get; set; }
        public Nullable<int> HrDepartment { get; set; }
        public string FatherName { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PlaceOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> NoOfChildren { get; set; }
        public Nullable<bool> IsAirTicket { get; set; }
        public string UAEAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public string PassportNo { get; set; }
        public string PassportCountryIssue { get; set; }
        public Nullable<System.DateTime> PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
    }
}
