//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int Id { get; set; }
        public string SchoolNameEn { get; set; }
        public string SchoolNameAr { get; set; }
        public string sKey { get; set; }
        public string AddressEn { get; set; }
        public string AddressAr { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string POBox { get; set; }
        public string SchoolType { get; set; }
        public string LicenseNo { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<System.DateTime> ChangeDateAt { get; set; }
        public Nullable<bool> EntrExamNeeded { get; set; }
        public Nullable<bool> DependsOnFees { get; set; }
        public Nullable<decimal> ExamFees { get; set; }
        public Nullable<bool> ShowMarks { get; set; }
        public string DirectorName { get; set; }
        public string GuardianName { get; set; }
        public string DirectorAddress { get; set; }
        public string GuardianAddress { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> EducationZoneID { get; set; }
        public byte[] SchoolLogo { get; set; }
        public string ReportRegisterBy { get; set; }
        public string ReportCheckedBy { get; set; }
        public byte[] ReportLogo { get; set; }
        public string EnReportRegisterBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
