//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeedBackReport
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Class { get; set; }
        public string StudentCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string Remarks { get; set; }
        public string ApprovedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
