//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_StudentDtl
    {
        public int Id { get; set; }
        public string AcademicYear { get; set; }
        public int AccountID { get; set; }
        public string RollNo { get; set; }
        public string Status { get; set; }
        public string PrevStatus { get; set; }
        public string Prevclass { get; set; }
        public Nullable<int> Class { get; set; }
        public string VClass { get; set; }
        public string Bus_no { get; set; }
        public Nullable<System.DateTime> StartsFrom { get; set; }
        public string SSection { get; set; }
        public string FinalResult { get; set; }
        public string ReTestResult { get; set; }
        public Nullable<int> ClNo { get; set; }
        public string OptionalDivision { get; set; }
        public Nullable<System.DateTime> ActualJoiningDate { get; set; }
        public string shift { get; set; }
        public Nullable<bool> Admission { get; set; }
        public Nullable<bool> ClassNo { get; set; }
        public Nullable<bool> Reregistered { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<bool> IdPrinted { get; set; }
        public string AdmissionSchedule { get; set; }
        public string FeeSchedule { get; set; }
        public string TransSchedule { get; set; }
        public string DiscountSchedule { get; set; }
        public string TranDiscountSchedule { get; set; }
        public Nullable<bool> FeeDiscount { get; set; }
        public Nullable<bool> TranDiscount { get; set; }
        public string Program { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<System.DateTime> TranStartDate { get; set; }
        public string TransScheduleDummy { get; set; }
        public string ReRegistrationStatus { get; set; }
        public Nullable<System.DateTime> ReRegistrationDate { get; set; }
        public string SubStatus { get; set; }
        public string Followup { get; set; }
        public Nullable<bool> Photoallowed { get; set; }
        public Nullable<bool> mobile_app_access { get; set; }
        public Nullable<bool> ReRegBlock { get; set; }
        public string Bus_Mode { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<int> Optional_Bus_No { get; set; }
        public Nullable<int> Optional_Stop_No { get; set; }
        public string DiscountRemarks { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
        public string MonthlyPayment { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
