//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_StudentMst
    {
        public int Id { get; set; }
        public int AccountID { get; set; }
        public string StudentStatus { get; set; }
        public string Sex { get; set; }
        public string Religion { get; set; }
        public string MotherTongue { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOFBirth { get; set; }
        public string SLanguage { get; set; }
        public string OpLanguage1 { get; set; }
        public string OpLanguage2 { get; set; }
        public string OpDivision { get; set; }
        public string PrevSchool { get; set; }
        public string PrevPlace { get; set; }
        public string MinistryStatus { get; set; }
        public string RegisterNo { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Emirates { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string PassportIssuePlace { get; set; }
        public string PassportStatus { get; set; }
        public string VisaNo { get; set; }
        public Nullable<System.DateTime> VisaIssueDate { get; set; }
        public Nullable<System.DateTime> VisaExpiryDate { get; set; }
        public string VisaIssuePlace { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string LeavingReason { get; set; }
        public string JoiningClass { get; set; }
        public string JoiningDivision { get; set; }
        public string TcType { get; set; }
        public string TcDetails { get; set; }
        public Nullable<System.DateTime> TcDate { get; set; }
        public string tcto { get; set; }
        public string JoiningAcademicYear { get; set; }
        public string ArabNonArab { get; set; }
        public string SportsHouse { get; set; }
        public string FeeSchedule { get; set; }
        public string TransSchedule { get; set; }
        public string ActivitySchedule { get; set; }
        public string DiscountSchedule { get; set; }
        public bool Termwise { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string VisaStatus { get; set; }
        public string Email { get; set; }
        public string AdmissionSchedule { get; set; }
        public Nullable<bool> Blocked { get; set; }
        public string PrevDivision { get; set; }
        public Nullable<bool> FeeDiscount { get; set; }
        public Nullable<bool> TranDiscount { get; set; }
        public string PdcRemarks { get; set; }
        public Nullable<System.DateTime> TestingDate { get; set; }
        public string RelationContactsActual { get; set; }
        public Nullable<bool> EntranceExam { get; set; }
        public string TranDiscountSchedule { get; set; }
        public Nullable<bool> DocEmiratesID { get; set; }
        public Nullable<bool> DocVisa { get; set; }
        public Nullable<bool> DocSponsorPassport { get; set; }
        public Nullable<bool> DocSponsorVisa { get; set; }
        public Nullable<bool> DocReportCard { get; set; }
        public string Country { get; set; }
        public Nullable<bool> DocMedicalReport { get; set; }
        public Nullable<bool> DocFamilyBook { get; set; }
        public Nullable<bool> DocSponsorID { get; set; }
        public string fincode { get; set; }
        public string grnumber { get; set; }
        public Nullable<System.DateTime> ReRegistrationDate { get; set; }
        public Nullable<System.DateTime> LastAttendenceDate { get; set; }
        public string StudMobile { get; set; }
        public string LivingWith { get; set; }
        public string Custody { get; set; }
        public string Memo { get; set; }
        public string CourtAccess { get; set; }
        public string SpecialNeed { get; set; }
        public string SpecialNeedCategory { get; set; }
        public string SpecialNeedDescription { get; set; }
        public string RequiredAttention { get; set; }
        public string isgeneral { get; set; }
    }
}
