//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Class
    {
        public int Id { get; set; }
        public string Class { get; set; }
        public string Division { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string Strength { get; set; }
        public string Block { get; set; }
        public string Room { get; set; }
        public Nullable<int> StaffIDA { get; set; }
        public string Shift { get; set; }
        public string Building { get; set; }
        public string Section { get; set; }
    }
}
