//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermMaster
    {
        public int Id { get; set; }
        public int Academic_Year_Id { get; set; }
        public string Term_Date { get; set; }
        public string School_Id { get; set; }
        public int Term_Name { get; set; }
        public Nullable<System.DateTime> Marks_CutOff_Date { get; set; }
        public Nullable<bool> IsResultPublished { get; set; }
        public Nullable<bool> isCurrent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> PermanentDelete { get; set; }
    }
}
