//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyMeetingSchedule
    {
        public int Id { get; set; }
        public string Day { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string TeacherName { get; set; }
        public Nullable<int> ClassId { get; set; }
    }
}
